import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:radio_escola/models/progress.dart';
import 'package:radio_escola/services/spaced_repetition.dart';

void main() {
  group('parity with the website implementation', () {
    // The point of this port is that a question reviewed on the phone and one
    // reviewed on the site end up on the same schedule. These vectors were
    // generated by running the real `calculateSM2` from lib/spaced-repetition/
    // sm2.ts over sequences that exercise the fixed early intervals, the ease
    // factor floor, failure resets and the 365-day cap. Regenerating them is
    // how you'd prove the two are still in step after changing either side.
    final fixture = json.decode(
      File('test/fixtures/sm2_reference.json').readAsStringSync(),
    ) as Map<String, dynamic>;
    final now = fixture['now'] as int;
    final cases = fixture['cases'] as List;

    test('the fixture actually covers something', () {
      final steps = cases.fold<int>(
          0, (sum, c) => sum + (c['steps'] as List).length);
      expect(cases, isNotEmpty);
      expect(steps, greaterThanOrEqualTo(60));
    });

    for (final (index, testCase) in cases.indexed) {
      final sequence = (testCase['seq'] as List).cast<int>();
      final steps = testCase['steps'] as List;

      test('case $index: ratings $sequence match the TypeScript', () {
        SpacedRepetitionStats? stats;

        for (final (step, expected) in steps.indexed) {
          final result = calculateSm2(
            quality: sequence[step],
            current: stats,
            now: now,
          );
          stats = result.stats;

          final where = 'sequence $sequence, step $step';
          expect(stats.interval, expected['interval'], reason: 'interval @ $where');
          expect(stats.repetitionNumber, expected['repetitionNumber'],
              reason: 'repetitionNumber @ $where');
          expect(stats.nextReviewDate, expected['nextReviewDate'],
              reason: 'nextReviewDate @ $where');
          expect(result.wasCorrect, expected['wasCorrect'],
              reason: 'wasCorrect @ $where');
          expect(stats.easeFactor,
              closeTo(expected['easeFactor'] as double, 1e-9),
              reason: 'easeFactor @ $where');
        }
      });
    }
  });

  group('calculateSm2', () {
    test('a first good review is due in a day', () {
      final result = calculateSm2(quality: ReviewQuality.good.rating, now: 0);

      expect(result.wasCorrect, isTrue);
      expect(result.stats.interval, 1);
      expect(result.stats.repetitionNumber, 1);
      expect(result.stats.nextReviewDate, Duration.millisecondsPerDay);
    });

    test('quality 3 is the pass mark', () {
      expect(calculateSm2(quality: 2, now: 0).wasCorrect, isFalse);
      expect(calculateSm2(quality: 3, now: 0).wasCorrect, isTrue);
    });

    test('intervals grow 1, 3, then by the ease factor', () {
      SpacedRepetitionStats? stats;
      final intervals = <int>[];
      for (var i = 0; i < 5; i++) {
        final result =
            calculateSm2(quality: ReviewQuality.good.rating, current: stats, now: 0);
        stats = result.stats;
        intervals.add(stats.interval);
      }

      expect(intervals, [1, 3, 8, 20, 50]);
    });

    test('a failure resets the ladder and drops the ease factor by 0.2', () {
      SpacedRepetitionStats? stats;
      for (var i = 0; i < 4; i++) {
        stats = calculateSm2(
                quality: ReviewQuality.good.rating, current: stats, now: 0)
            .stats;
      }
      final before = stats!;
      expect(before.interval, greaterThan(3));

      final after =
          calculateSm2(quality: ReviewQuality.again.rating, current: before, now: 0)
              .stats;

      expect(after.interval, 1);
      expect(after.repetitionNumber, 1);
      expect(after.easeFactor, closeTo(before.easeFactor - 0.2, 1e-9));
    });

    test('the ease factor never falls below the floor', () {
      SpacedRepetitionStats? stats;
      for (var i = 0; i < 20; i++) {
        stats = calculateSm2(
                quality: ReviewQuality.again.rating, current: stats, now: 0)
            .stats;
      }

      expect(stats!.easeFactor, Sm2Config.minEaseFactor);
    });

    test('the ease factor never rises above the ceiling', () {
      SpacedRepetitionStats? stats;
      for (var i = 0; i < 20; i++) {
        stats = calculateSm2(
                quality: ReviewQuality.easy.rating, current: stats, now: 0)
            .stats;
      }

      expect(stats!.easeFactor, Sm2Config.maxEaseFactor);
    });

    test('intervals are capped at a year', () {
      SpacedRepetitionStats? stats;
      for (var i = 0; i < 20; i++) {
        stats = calculateSm2(
                quality: ReviewQuality.easy.rating, current: stats, now: 0)
            .stats;
      }

      expect(stats!.interval, Sm2Config.maxInterval);
    });

    test('easy beats good from the same starting point', () {
      final start = calculateSm2(quality: ReviewQuality.good.rating, now: 0).stats;
      final afterGood =
          calculateSm2(quality: ReviewQuality.good.rating, current: start, now: 0);
      final afterEasy =
          calculateSm2(quality: ReviewQuality.easy.rating, current: start, now: 0);

      expect(afterEasy.stats.interval,
          greaterThanOrEqualTo(afterGood.stats.interval));
    });
  });

  group('isReviewDue', () {
    test('a question never reviewed is due', () {
      expect(isReviewDue(null), isTrue);
    });

    test('is due once the review date has arrived', () {
      final stats = calculateSm2(quality: ReviewQuality.good.rating, now: 0).stats;

      expect(isReviewDue(stats, now: 0), isFalse);
      expect(isReviewDue(stats, now: Duration.millisecondsPerDay - 1), isFalse);
      expect(isReviewDue(stats, now: Duration.millisecondsPerDay), isTrue);
    });
  });

  group('daysUntilReview', () {
    test('is zero for a question never reviewed', () {
      expect(daysUntilReview(null), 0);
    });

    test('counts down and goes negative when overdue', () {
      final stats = calculateSm2(quality: ReviewQuality.good.rating, now: 0).stats;

      expect(daysUntilReview(stats, now: 0), 1);
      expect(
        daysUntilReview(stats, now: 3 * Duration.millisecondsPerDay),
        -2,
      );
    });
  });

  group('intervalPreviews', () {
    test('offers a preview for every button', () {
      final previews = intervalPreviews(null, now: 0);

      expect(previews.keys, containsAll(ReviewQuality.values));
      expect(previews[ReviewQuality.again], 1);
    });

    test('previews match what the rating actually does', () {
      final current =
          calculateSm2(quality: ReviewQuality.good.rating, now: 0).stats;
      final previews = intervalPreviews(current, now: 0);

      for (final quality in ReviewQuality.values) {
        final actual =
            calculateSm2(quality: quality.rating, current: current, now: 0);
        expect(previews[quality], actual.stats.interval,
            reason: 'preview for ${quality.name}');
      }
    });

    test('previews are ordered, so the buttons read sensibly', () {
      SpacedRepetitionStats? stats;
      for (var i = 0; i < 3; i++) {
        stats = calculateSm2(
                quality: ReviewQuality.good.rating, current: stats, now: 0)
            .stats;
      }
      final previews = intervalPreviews(stats, now: 0);

      expect(previews[ReviewQuality.again]!,
          lessThanOrEqualTo(previews[ReviewQuality.hard]!));
      expect(previews[ReviewQuality.hard]!,
          lessThanOrEqualTo(previews[ReviewQuality.good]!));
      expect(previews[ReviewQuality.good]!,
          lessThanOrEqualTo(previews[ReviewQuality.easy]!));
    });
  });
}
